version: '3'
services:
  app:
    stdin_open: true
    tty: true
    build:
      dockerfile: Dockerfile
      context: .
    volumes:
     - ./app:/home/app/
  api:
    build:
      dockerfile: Dockerfile
      context: .
    volumes:
     - ./app:/home/app/
    volumes:
     - ./api:/home/api/