version: '3'
services:
  app:
    stdin_open: true
    tty: true
    build:
      dockerfile: Dockerfile
      context: .
    volumes:
     - ./app:/home/app/
  api:
    tty: true
    ports:
     - "3000:3000"
    build:
      dockerfile: Dockerfile-api
      context: .
    volumes:
     - ./app:/home/app/
     - ./api:/home/api/
    entrypoint:
      - node
      - ../api